# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

from dataclasses import dataclass
from unittest.mock import patch

import carb.settings

import omni.client
import omni.structuredlog
from omni.kit.test import AsyncTestCase
from omni.physxclashdetectiontelemetry.clash_telemetry import ClashDetectionViewportTelemetry, ClashTelemetry


@dataclass
class StatsClass:
    nbMeshes: float = 0.0
    nbSharedMeshes: float = 0.0
    nbCookedMeshes: float = 0.0


class TelemetryTest(AsyncTestCase):

    def __init__(self, tests=()):
        super().__init__(tests)
        self._clash_telemetry_logging_orig_val = ClashTelemetry.debug_logging
        self._settings = carb.settings.get_settings()

    # Before running each test
    def setUp(self):
        super().setUp()
        ClashTelemetry.debug_logging = True
        ClashTelemetry.telemetry_is_enabled = True
        self._clash_telemetry_enabled_orig_val = self._settings.get_as_bool(omni.physxclashdetectiontelemetry.SETTING_CLASH_DETECTION_TELEMETRY_ENABLED)
        self._settings.set_bool(omni.physxclashdetectiontelemetry.SETTING_CLASH_DETECTION_TELEMETRY_ENABLED, True)

    def tearDown(self):
        super().tearDown()
        ClashTelemetry.debug_logging = self._clash_telemetry_logging_orig_val
        self._settings.set_bool(omni.physxclashdetectiontelemetry.SETTING_CLASH_DETECTION_TELEMETRY_ENABLED, self._clash_telemetry_enabled_orig_val)
        ClashTelemetry.telemetry_is_enabled = self._clash_telemetry_enabled_orig_val

    @patch.object(omni.structuredlog, 'send_event')
    async def test_telemetry_events_and_autogenerated_methods(self, mock_structuredlog_sendevent):
        ClashTelemetry.log_elapsed_query_run(2.2, 0.4)
        ClashTelemetry.log_clash_data_file_size(20.5)
        ClashTelemetry.log_viewport_telemetry(ClashDetectionViewportTelemetry(2.2, 2.2, 2.2))
        ClashTelemetry.log_local_vs_remote_stage(True)
        ClashTelemetry.log_soft_vs_hard_query(False)
        ClashTelemetry.log_dynamic_vs_static_query(True)
        ClashTelemetry.log_num_of_found_overlaps(324)
        ClashTelemetry.log_used_system_memory(2983)
        ClashTelemetry.log_total_num_of_overlapping_tris(222)
        stats = StatsClass()
        ClashTelemetry.log_clash_data_meshes_stats(stats)
        assert mock_structuredlog_sendevent.call_count == 10
