[package]
version = "110.0.1"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarily for displaying extension info in UI
title = "Clash Detection Viewport"
description = "Clash Detection Viewport visualization."

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Clash Detection"

# Keywords for the extension
keywords = ["clash", "detection", "physics", "PhysX"]

# Location of change log file in target (final) folder of extension, relative to the root. Can also be just a content
# of it instead of file path. More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

support_level = "Example"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.physx.clashdetection.telemetry" = { version = "110.0.1", exact = true }
"omni.kit.viewport.menubar.core" = {}
"omni.kit.viewport.window" = {}
"omni.kit.viewport.utility" = {}
"usdrt.scenegraph" = {}
"omni.warp.core" = {}

# Main python module this extension provides, it will be publicly available as "import omni.example.hello".
[[python.module]]
name = "omni.physxclashdetectionviewport"

[settings]
exts."omni.physx.clashdetection.viewport".visible = true
exts."omni.physx.clashdetection.viewport".order = 0

[[test]]
args = [
    "--/rtx-transient/post/aa/limitedOps=false",
    "--/renderer/enabled=rtx",
    "--/renderer/active=rtx",
    "--/rtx/hydra/materialSyncLoads=true",
    "--/rtx/useViewLightingMode=true",
    "--/rtx/rtpt/maxBounces=2",
    "--/rtx/rtpt/maxSpecularAndTransmissionBounces=2",
    "--/rtx/rtpt/cached/enabled=true",
    "--/rtx/rtpt/lightcache/cached/enabled=true",
    "--/rtx/rendermode='RaytracedLighting'",
    "--/rtx/rtpt/spp=1",
    "--/app/window/width=1600",
    "--/app/window/height=1024",
    "--/app/asyncRendering=false",
    "--no-window",
    "--/plugins/carb.tasking.plugin/stuckCheckSeconds=0",
    "--/renderer/multiGpu/autoEnable=false",
    "--/renderer/multiGpu/enabled=false",
    "--/renderer/debug/validation/enabled=false",
    "--/omni.kit.plugin/syncUsdLoads=true",
    "--/exts/omni.kit.telemetry/skipDeferredStartup=true",
]
dependencies = [
    "omni.physx.clashdetection.anim",
    "omni.physx.clashdetection.ui",
    "omni.hydra.rtx",
    "omni.kit.stage_templates",
    "omni.physx.tests.visual",
    "omni.physx.tests",
    "omni.physx.clashdetection.testdata-110.0.1",
    "omni.hydra.usdrt_delegate", # Do not use omni.population see https://nvbugspro.nvidia.com/bug/5459396
]
"filter:platform"."linux-aarch64".enabled = false
