# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

from dataclasses import dataclass

import carb

from . import autogenerated_telemetry_module


@dataclass
class ClashDetectionViewportTelemetry:
    """Telemetry data for Clash Detection Viewport.

    Attributes:
    - inited_seconds (float): Tracks how many seconds has the extension been active
    - focused_seconds (float): Tracks how many seconds has the extension been focused (user interaction)
    - visible_seconds (float): Tracks how many seconds has the extension been visible (no user interaction)
    """

    inited_seconds: float = 0.0
    focused_seconds: float = 0.0
    visible_seconds: float = 0.0


# Please check ClashTelemetry.md for the documentation of the telemetry data.
class ClashTelemetry:
    """A class for logging telemetry data related to Clash Detection operations.

    This class provides several static methods to log various telemetry events such as processing and serialization timings, viewport telemetry, and memory usage. The telemetry data can be used for performance monitoring and debugging purposes.
    """

    debug_logging: bool = True  # echoes telemetry events on the carb.log_info
    telemetry_is_enabled: bool = False  # persistent-setting controlled variable to actually do telemetry or not

    @staticmethod
    def log_elapsed_query_run(clash_processing_elapsed: float, clash_serialization_elapsed: float) -> None:
        """Logs processing and serialization timings after a query finished running.

        Args:
            clash_processing_elapsed (float): Time taken for clash processing in seconds.
            clash_serialization_elapsed (float): Time taken for clash serialization in seconds.
        """
        if ClashTelemetry.telemetry_is_enabled:
            autogenerated_telemetry_module.log_elapsed_query_run_send_event(
                clash_processing_elapsed, clash_serialization_elapsed
            )
            if ClashTelemetry.debug_logging:
                carb.log_info(f"ClashTelemetry: clash_processing_elapsed={clash_processing_elapsed} seconds")
                carb.log_info(f"ClashTelemetry: clash_serialization_elapsed={clash_serialization_elapsed} seconds")

    @staticmethod
    def log_clash_data_file_size(database_disk_size_mb: float) -> None:
        """Logs size of current clash detection data file in MB.

        Args:
            database_disk_size_mb (float): Size of the database file in megabytes.
        """
        if ClashTelemetry.telemetry_is_enabled:
            autogenerated_telemetry_module.log_clash_data_file_size_send_event(database_disk_size_mb)
            if ClashTelemetry.debug_logging:
                carb.log_info(f"ClashTelemetry: database_disk_size_mb={database_disk_size_mb} MiB")

    @staticmethod
    def log_viewport_telemetry(clash_viewport_telemetry: ClashDetectionViewportTelemetry) -> None:
        """Logs viewport telemetry events on stage CLOSING event.

        Args:
            clash_viewport_telemetry (ClashDetectionViewportTelemetry): Telemetry data for Clash Detection Viewport.
        """
        if ClashTelemetry.telemetry_is_enabled:
            autogenerated_telemetry_module.log_viewport_telemetry_send_event(clash_viewport_telemetry.__dict__)
            if ClashTelemetry.debug_logging:
                carb.log_info(
                    f"ClashDetectionViewportTelemetry.inited_seconds={clash_viewport_telemetry.inited_seconds}"
                )
                carb.log_info(
                    f"ClashDetectionViewportTelemetry.visible_seconds={clash_viewport_telemetry.visible_seconds}"
                )
                carb.log_info(
                    f"ClashDetectionViewportTelemetry.focused_seconds={clash_viewport_telemetry.focused_seconds}"
                )

    @staticmethod
    def log_local_vs_remote_stage(local: bool) -> None:
        """Logs if opened stage was local (True) or remote (False).

        Args:
            local (bool): Indicates if the stage was local.
        """
        if ClashTelemetry.telemetry_is_enabled:
            autogenerated_telemetry_module.log_local_vs_remote_stage_send_event(local)
            if ClashTelemetry.debug_logging:
                carb.log_info(f"ClashTelemetry: local_vs_remote_stage={'local' if local else 'remote'}")

    @staticmethod
    def log_soft_vs_hard_query(soft: bool) -> None:
        """Logs if executed clash detection query was looking for soft (True) or hard (False) clashes.

        Args:
            soft (bool): Indicates if the query was for soft clashes.
        """
        if ClashTelemetry.telemetry_is_enabled:
            autogenerated_telemetry_module.log_soft_vs_hard_query_send_event(soft)
            if ClashTelemetry.debug_logging:
                carb.log_info(f"ClashTelemetry: soft_vs_hard_query={'soft' if soft else 'hard'}")

    @staticmethod
    def log_dynamic_vs_static_query(dynamic: bool) -> None:
        """Logs if executed clash detection query was dynamic (True) or static (False).

        Args:
            dynamic (bool): Indicates if the query was dynamic.
        """
        if ClashTelemetry.telemetry_is_enabled:
            autogenerated_telemetry_module.log_dynamic_vs_static_query_send_event(dynamic)
            if ClashTelemetry.debug_logging:
                carb.log_info(f"ClashTelemetry: dynamic_vs_static_query={'dynamic' if dynamic else 'static'}")

    @staticmethod
    def log_num_of_found_overlaps(num_overlaps: int) -> None:
        """Logs number of overlaps (clashes) found during the clash detection process.

        Args:
            num_overlaps (int): Number of overlaps found.
        """
        if ClashTelemetry.telemetry_is_enabled:
            autogenerated_telemetry_module.log_num_of_found_overlaps_send_event(num_overlaps)
            if ClashTelemetry.debug_logging:
                carb.log_info(f"ClashTelemetry: number_of_found_overlaps={num_overlaps}")

    @staticmethod
    def log_used_system_memory(memory_size: int) -> None:
        """Logs used system memory for the executed clash detection process in bytes.

        Args:
            memory_size (int): Used system memory in bytes.
        """
        if ClashTelemetry.telemetry_is_enabled:
            autogenerated_telemetry_module.log_used_system_memory_send_event(memory_size)
            if ClashTelemetry.debug_logging:
                carb.log_info(f"ClashTelemetry: used_system_memory={float(memory_size) / 1024.0 / 1024.0} MiB")

    @staticmethod
    def log_total_num_of_overlapping_tris(num_triangles: int) -> None:
        """Logs total number of overlapping triangles found during the clash detection process.
        For each dynamic clash returns max number of overlapping triangles during the clash duration.

            Args:
                num_triangles (int): Number of overlapping triangles found.
        """
        if ClashTelemetry.telemetry_is_enabled:
            autogenerated_telemetry_module.log_total_num_of_overlapping_tris_send_event(num_triangles)
            if ClashTelemetry.debug_logging:
                carb.log_info(f"ClashTelemetry: total_num_of_overlapping_tris={num_triangles}")

    @staticmethod
    def log_clash_data_meshes_stats(meshes_stats) -> None:
        """Logs low level mesh-related stats like number of processed meshes and cooked meshes.

        Args:
            meshes_stats (object): Object containing mesh statistics.
        """
        if ClashTelemetry.telemetry_is_enabled:
            # Small workaround since binding variables don't have __dict__
            autogenerated_telemetry_module.log_clash_data_meshes_stats_send_event(
                {
                    "nbMeshes": meshes_stats.nbMeshes,
                    "nbSharedMeshes": meshes_stats.nbSharedMeshes,
                    "nbCookedMeshes": meshes_stats.nbCookedMeshes,
                }
            )
            if ClashTelemetry.debug_logging:
                carb.log_info(f"ClashTelemetry: clash detection stats={meshes_stats}")
